name: world_time_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/day.png
    - assets/night.png
    - assets/germany.png
    - assets/uk.png
    - assets/usa.png
    - assets/japan.png
    - assets/australia.png
    - assets/kenya.png
    - assets/uae.png